### ISSUE TITLE
Merge queues are not supported

### ISSUE THREAD

**Issue by edgarrmondragon** [Ezard/semantic-prs#406]
### Describe the bug

When adding a PR to a [merge queue](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#about-merge-queues) in a repo where this check is required according to branch protection rules, it hangs with "Waiting for status to be reported".

I think the fix could be as simple as triggering this check on a `pull_request.enqueued` event.

Thanks!

### semantic.yml contents

```yml
# Config ref: https://github.com/Ezard/semantic-prs

# Validate the PR title, and ignore all commit messages
titleOnly: true

# Provides a custom URL for the "Details" link, which appears next to the success/failure message from the app:
targetUrl: https://docs.meltano.com/contribute/merge#semantic-prs

# The values allowed for the "type" part of the PR title/commit message.
# e.g. for a PR title/commit message of "feat: add some stuff", the type would be "feat"
types:
  - ci
  - chore
  - build
  - break
  - change
  - docs
  - feat
  - fix
  - perf
  - refactor
  - revert
  - style
  - test

# The values allowed for the "scope" part of the PR title/commit message.
# e.g. for a PR title/commit message of "feat(awesome-feature): add some stuff",
#      the scope would be "awesome-feature"
scopes:
  - core
  - cli
  - cloud
  - deps
  - deps-dev
```
