### ISSUE TITLE
semantic.yaml not being read?

### ISSUE THREAD

**Issue by amirasyraf** [Ezard/semantic-prs#517]
### Describe the bug

I've set `targetUrl` to a custom URL, but as the screenshot shows below, it's not being used:

![image](https://github.com/Ezard/semantic-prs/assets/15522007/737463dc-9117-4497-b6fd-e091fbc2f5cc)

The semantic.yaml file is already merged to main and the branch PR is up to date with main.

In fact, I'm not even sure it's using the semantic.yaml config at all, as I've set `anyCommit: false`, and `titleAndCommits: true` and it's only checking for commit message instead of both.

The file is located at `.github/semantic.yaml`

### semantic.yml contents

```yml
enabled: true

titleOnly: false

commitsOnly: false

titleAndCommits: true

anyCommit: false

types:
  - feat
  - fix
  - docs
  - refactor
  - ci
  - chore

allowMergeCommits: true

allowRevertCommits: false

targetUrl: https://www.conventionalcommits.org/en/v1.0.0/
```

### Sample PR Title(s) (if relevant)

test

### Sample Commit Message(s) (if relevant)

feat: test
