### ISSUE TITLE
missing space in PR title does not get caught

### ISSUE THREAD

**Issue by scarf005** [Ezard/semantic-prs#562]
### Describe the bug

![image](https://github.com/Ezard/semantic-prs/assets/54838975/02d46453-8168-4d74-9224-a763f3ce269a)

from https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4329

### semantic.yml contents

```yml
enabled: true
titleOnly: true
targetUrl: 'https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/'
types:
  - feat
  - fix
  - docs
  - style
  - refactor
  - perf
  - test
  - build
  - ci
  - chore
  - revert

# irrelevant configs skipped   
```

https://github.com/cataclysmbnteam/Cataclysm-BN/blob/59eb28f4a7404d1ec2f4be1eaa387d4317a8a812/.github/semantic.yml

### Sample PR Title(s) (if relevant)

feat(content):Cooking with insect eggs
